features:
  module: models.gcpnet.features.factory.ProteinFeaturiser
  kwargs:
    representation: CA
    scalar_node_features:
      - amino_acid_one_hot
      - sequence_positional_encoding
      - alpha
      - kappa
      - dihedrals
    vector_node_features:
      - orientation
    edge_types:
      - knn_16
    scalar_edge_features:
      - edge_distance
    vector_edge_features:
      - edge_vectors

task:
  transform: null

encoder:
  module: models.gcpnet.models.graph_encoders.gcpnet.GCPNetModel
  kwargs:
    num_layers: 6
    emb_dim: 128
    node_s_emb_dim: 128
    node_v_emb_dim: 16
    edge_s_emb_dim: 32
    edge_v_emb_dim: 4
    r_max: 10.0
    num_rbf: 8
    activation: silu
    pool: sum
    module_cfg:
      norm_pos_diff: true
      scalar_gate: 0
      vector_gate: true
      scalar_nonlinearity: silu
      vector_nonlinearity: silu
      nonlinearities:
        - silu
        - silu
      r_max: 10.0
      num_rbf: 8
      bottleneck: 4
      vector_linear: true
      vector_identity: true
      default_bottleneck: 4
      predict_node_positions: false
      predict_node_rep: true
      node_positions_weight: 1.0
      update_positions_with_vector_sum: false
      enable_e3_equivariance: false
      pool: sum
    model_cfg:
      h_input_dim: 49
      chi_input_dim: 2
      e_input_dim: 9
      xi_input_dim: 1
      h_hidden_dim: 128
      chi_hidden_dim: 16
      e_hidden_dim: 32
      xi_hidden_dim: 4
      num_layers: 6
      dropout: 0.0
    layer_cfg:
      pre_norm: false
      use_gcp_norm: true
      use_gcp_dropout: true
      use_scalar_message_attention: true
      num_feedforward_layers: 2
      dropout: 0.0
      nonlinearity_slope: 0.01
      mp_cfg:
        edge_encoder: false
        edge_gate: false
        num_message_layers: 4
        message_residual: 0
        message_ff_multiplier: 1
        self_message: true

top_k: 30
num_positional_embeddings: 16
